name : deploy to staging 

on:
    push:
        branches:
            - main
jobs:
    job1 :
        runs-on: ubuntu-latest
        steps:
            - name : create new folder 
              run : mkdir new-folder
            - name : liste folders 
              run: ls -la

     
    job2 :
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name : liste folders 
              run : ls -la
            - name : storage managment 
              run : df -h
            - name : docker vesion 
              run : docker -v 
            - name : npm version 
              run : npm -v   


    job3 : 
        runs-on: ubuntu-latest
        needs: [job1, job2]
        steps :
            - name: clone repository
              uses: actions/checkout@v3
            - name: list files
              run : ls -al 


    job4:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: list folder 
              run: ls -al


    job5:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: liste folder and files 
              run: ls -la 
            