name : deploy to staging 

on:
    push:
        branches:
            [ main, master ]
jobs:
    job1 :
        runs-on: ubuntu-latest
        steps:
            - name : create new folder 
              run : mkdir new-folder
            - name : liste folders 
              run: ls -la

     
    job2 :
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name : liste folders 
              run : ls -la
            - name : storage managment 
              run : df -h
            - name : docker vesion 
              run : docker -v 
            - name : npm version 
              run : npm -v 
            - name : Nginx version 
              run: nginx -v 


    job3 : 
        runs-on: ubuntu-latest
        needs: [job1, job2]
        steps :
            - name: clone repository
              uses: actions/checkout@v3
            - name: list files
              run : ls -al 


    job4:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: list folder 
              run: ls -al


    job5:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: liste folder and files 
              run: ls -la 
           
    job6:
         runs-on: ubuntu-latest
         steps:
            - name: print hello world  
              run: echo "Hello World"

            - name: afficher la date 
              run: date


            - name: afficher le nom de l'utilisateur
              run: sudo su - whoam 



    job7: 
           runs-on: ubuntu-latest
           needs: job1
           steps:
            - name: print repository
              run: |
                echo " Repository: ${{ github.repository }}"
                echo "branche : ${{github.ref_name}}"
                echo "commit message : ${{github.event.head_commit.message}}"
                echo "commit author : ${{github.event.head_commit.author.name}}"
                echo "commit date : ${{github.event.head_commit.timestamp}}"
                echo "commit hash : ${{github.event.head_commit.id}}"

          

     